logging:
  level: INFO
  loggers:
    com.mycompany: DEBUG
server:
  rootPath: /api/*
database:
  driverClass: org.postgresql.Driver
  user: usercare
  password: usercare
  url: jdbc:postgresql://localhost:5435/dropwizard_events
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
dateFormat: yyyy-MM-dd'T'HH:mmZ

